[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
]
edition = "2021"
name = "trainbot-remote-application"
version = "0.1.0"
description = "Trainbot Remote"
keywords = ["nrf52833", "nrf", "nrf52", "microbit", "ble"]
resolver = "2"

[dependencies]
defmt = { version = "0.3" }
panic-probe = { version = "0.3", features = ["print-defmt"], optional = true }
panic-reset = { version = "0.1.1", optional = true }

drogue-device = { version = "0.1.0", default-features = false, features = ["time", "bsp+microbit"] }

#embassy-boot-nrf = { version = "0.1.0", default-features = false, features = ["softdevice"] }
embassy = { version = "0.1.0", default-features = false, features = [] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52833", "gpiote", "time-driver-rtc1"]}

cortex-m    = { version = "0.7.2" }
cortex-m-rt = "0.7"
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

nrf-softdevice = { version = "0.1.0", features = ["ble-central", "ble-gatt-client", "s140", "nrf52833"] }
nrf-softdevice-s140 = { version = "0.1.0" }
nrf-softdevice-defmt-rtt = { version = "0.1.0", optional = true }

[features]
default = [
    "panic-reset"
]
debug = [
    "panic-probe",
    "drogue-device/defmt",
    "nrf-softdevice/defmt",
    "embassy/defmt",
    "embassy-nrf/defmt",
#    "embassy-boot-nrf/defmt",
    "nrf-softdevice-defmt-rtt",
]

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 's'
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[patch.crates-io]
drogue-device = { git = "https://github.com/drogue-iot/drogue-device.git", rev = "7fab7189b3ea49dad7237989c270d6ab36e36b27" }
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "de7dd59fa9553a1a6b75ff09238c9529277b95e7" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "de7dd59fa9553a1a6b75ff09238c9529277b95e7" }
#embassy-boot = { git = "https://github.com/embassy-rs/embassy.git", rev = "de7dd59fa9553a1a6b75ff09238c9529277b95e7" }
#embassy-boot-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "de7dd59fa9553a1a6b75ff09238c9529277b95e7" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c584deaf9d9e941f18457934a4a463e078f380ec" }
nrf-softdevice-s140 = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c584deaf9d9e941f18457934a4a463e078f380ec" }
nrf-softdevice-defmt-rtt = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c584deaf9d9e941f18457934a4a463e078f380ec" }

#embassy = { path = "../../../../../../embassy/embassy" }
#embassy-nrf = { path = "../../../../../../embassy/embassy-nrf" }
#embassy-boot-nrf = { path = "../../../../../../embassy/embassy-boot/nrf" }
#embassy-boot = { path = "../../../../../../embassy/embassy-boot/boot" }
